#!/usr/bin/env bash
#displays the PID, along with the process name, of processes whose name contain the word bash.
pids=$(pgrep -f "bash")
for pid in $pids; do
  name=$(cat /proc/"$pid"/comm)
  echo "$pid $name"
done
