#!/usr/bin/env bash
# This script that stops 4-to_infinity_and_beyond process.
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
  kill "$pid"
  echo "Process with PID $pid and name 4-to_infinity_and_beyond has been stopped."
else
  echo "No process with name 4-to_infinity_and_beyond found."
fi
