#!/usr/bin/env bash
#  Bash script that stops 4-to_infinity_and_beyond process.
process_id=$(pgrep -f "4-to_infinity_and_beyond")
if [ -z "$process_id" ]; then
    echo "Process not running."
    exit 1
fi
pkill -f "4-to_infinity_and_beyond"
if ! pgrep -f "4-to_infinity_and_beyond" > /dev/null; then
    echo "Terminated"
    exit 0
else
    echo "Failed to terminate process."
    exit 1
fi
