#!/usr/bin/env bash
#  Bash script that stops 7-highlander process.
process_id=$(pgrep -f "7-highlander")
if [ -z "$process_id" ]; then
    echo "Process not running."
    exit 1
fi
pkill -f "7-highlander"
if ! pgrep -f "7-highlander" > /dev/null; then
    echo "I am invincible!!!"
    exit 0
fi
