#!/usr/bin/env bash
#  Bash script that stops 4-to_infinity_and_beyond process.
process_id=$(pgrep -f "7-highlander")
if [ -z "$process_id" ]; then
    echo "Process not running."
    exit 1
fi
pkill -f "7-highlander"
if ! pgrep -f "7-highlander" > /dev/null; then
    echo "Process terminated successfully."
    exit 0
else
    echo "Failed to terminate process."
    exit 1
fi
