#!/usr/bin/env bash
# This script displays Best School 10 times, but for the 9th iteration, disp
x=1
while [ $x -le 10 ]
do
  echo "Best School"
  x=$((x + 1))
  if x=$((x = 9))
   then echo "Hi"
  fi
done
