#!/usr/bin/env bash
# This script displays Best School 10 times, but for the 9th iteration, disp
x=0
while [ $x -le 10 ]
do
  echo "Best School"
  x=$((x + 1))
  if [ $x -eq 9 ];
   then echo "Hi"
  fi
done
