#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration etc.
x=1
while [ $x -le 10 ]
do
  x=$((x + 1))
  if [ $x -eq 4 ]; then
     echo "bad luck"
  elif [ $x -eq 7 ]; then 
     echo "good luck"
  else
     echo "Best School"
  fi 
done
