#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration etc.
x=1
while [ $x -le 10 ]
do
  echo "Best School"
  x=$((x + 1))
  if x=$(( x > 4)) 
   echo "bad luck"
   else if x=$(( x > 8))
    echo "good luck"
   fi 
done
