#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
hours=0
minutes=1
while [ $hours -le 12 ]
do
  while [ $minutes -le 59 ]
  echo "Hour: $hours"  
  do    
    echo "$minutes"
    minutes=$((minutes+1))
  done
  minutes=1
  hours=$((hours+1))
done
