#!/usr/bin/env bash
# This script displays the content of the current directory in list format.
for file in *
do
    if [[ $file == *-* ]]; then
        first_dash=${file#*-}
        echo "$first_dash"
    else
        echo "$file"
    fi
done
